### ISSUE TITLE
About align in Preprocessing step

### ISSUE THREAD

**Issue by zhih-li** [yeongjoonJu/Occlusion-Robust-3D-Face-CFR-GAN#1]
Thanks for your greate work! I want to train my model following the readme file , and I noticed you remind that **You must align images with align.py** in Preprocessing step. 
So should I first execute align.py in origin datasets to get the aligned datasets, and then execute the create_train_stage1.py using the aligned datasets path as a parameter?
Thanks again!

**Comment by yeongjoonJu** [comment]
Yes, you understood perfectly!

**Comment by zhih-li** [comment]
> 

really thanks ！
